image: gradle:alpine

before_script:
  - echo "Start CI"
  - cd TourGuide

stages:
  - build
  - test
  - package

build:
  stage: build
  script:
    - echo "Compiling code..."
    - ./gradlew assemble
    - echo "Compiling completed" 
    
test:
  stage: test
  script:
    - echo "Starting tests..."
    - ./gradlew test
    - echo "Tests completed"

package:
  stage: package
  script:
    - echo "Creating jar file"
    - ./gradlew bootJar
    - echo "jar file created"
  artifacts:
    paths:
      - TourGuide/build/libs/*.jar

after_script:
  - echo "End CI "
